mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#开发配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
    port: 8082